/****************************************************************
*****************************************************************
    _/    _/  _/_/_/  _/       Numerical Simulation Laboratory
   _/_/  _/ _/       _/       Physics Department
  _/  _/_/    _/    _/       Universita' degli Studi di Milano
 _/    _/       _/ _/       Prof. D.E. Galli
_/    _/  _/_/_/  _/_/_/_/ email: Davide.Galli@unimi.it
*****************************************************************
*****************************************************************/

#include <iostream>
#include <fstream>
#include <string>
#include "random.h"

using namespace std;
 
int main (int argc, char *argv[])
{

// ================================= =================================  =========================
  
  if(argc < 2)
    {
      cout << "Usage: " << argv[0] << " <number of throws (max 1000000)> "<< endl;
      return -1;
    }
  if(atoi(argv[1]) > 1000000)
    {
      cout << "Number of throws too high " << endl;
      cout << "Usage: " << argv[0] << " <number of throws (max 1000000)> " << endl;
      return -1;
    }

  int throws = atoi(argv[1]);
  
  // ------------------------------ ------------------------------ ------------------------------
   Random rnd;
   int seed[4];
   int p1, p2;
   ifstream Primes("Primes");
   if (Primes.is_open()){
      Primes >> p1 >> p2 ;
   } else cerr << "PROBLEM: Unable to open Primes" << endl;
   Primes.close();

   ifstream input("seed.in");
   string property;
   if (input.is_open()){
      while ( !input.eof() ){
         input >> property;
         if( property == "RANDOMSEED" ){
            input >> seed[0] >> seed[1] >> seed[2] >> seed[3];
            rnd.SetRandom(seed,p1,p2);
         }
      }
      input.close();
   } else cerr << "PROBLEM: Unable to open seed.in" << endl;

   // ================================= =================================  =================================
   // Writing the values generated by rnd.Rannyu() into the file random_out.txt
   ofstream output("random_out.txt");
   if (output)
     {  
       for(int i=0; i<throws; i++){
	 output << rnd.Rannyu() << endl;
       }
     }
   else
     {
       cout << "PROBLEM: Unable to open random_out.txt" << endl;
     }

   // ------------------------------ ------------------------------ ------------------------------

   // ================================= =================================  =================================
   // Writing the values generated by rnd.Exponential() into the file random_exponential_out.txt

   ofstream output_exp("random_exponential_out.txt");

   if(output_exp)
     {
       for(int i = 0; i<throws; i++)
       output_exp << rnd.Exponential(1) << endl;
     }
   else
     {
       cout << "PROBLEM: Unable to open random_exponential_out.txt" << endl;
     }

   
   // ------------------------------ ------------------------------ ------------------------------

   // ================================= =================================  =================================
   // Writing the values generated by rnd.Lorentzian() into the file random_lorentzian_out.txt

   ofstream output_lorentzian("random_lorentzian_out.txt");

   if(output_lorentzian)
     {
       for(int i=0; i<throws; i++)
	 output_lorentzian << rnd.Lorentzian(1,0) << endl; 
     }
   else
     {
       cout << "PROBLEM: Unable to open random_lorentzian_out.txt" << endl;
     }
   
   rnd.SaveSeed();
   return 0;
}

/****************************************************************
*****************************************************************
    _/    _/  _/_/_/  _/       Numerical Simulation Laboratory
   _/_/  _/ _/       _/       Physics Department
  _/  _/_/    _/    _/       Universita' degli Studi di Milano
 _/    _/       _/ _/       Prof. D.E. Galli
_/    _/  _/_/_/  _/_/_/_/ email: Davide.Galli@unimi.it
*****************************************************************
*****************************************************************/
